### ISSUE TITLE
Provide surface analysis to FV3 for JEDI-based cycled system

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/JEDI-Eval#66]
Extract surface analysis part of the JGLOBAL_ATMOS_ANALYSIS into its own j-job.

**Comment by RussTreadon-NOAA** [comment]
The following test was run on Venus

- set up v16ops using $NWROOTp3/gfs.v16.1.5.   Run 2021112912 gdas cycle from prep up through gdasfcst and gdasefcs01.   Prime parallel with operational files.   Job anal executed global_cycle and gaussian_sfcanl.   gldas ran but did nothing since the 12Z cycle was being run.
 - set up v16test using checkout of gfs.v16.1.5 tag.   Move global_cycle and gausian_sfcanl from anal to gldas.   Doing so modified the anal and gldas j-jobs and ex scripts.   env/WCOSS_DELL_P3.env was also updated.   The global_cycle and gaussian_sfcanl pieces were moved from anal to gldas.   config.resources was correspondingly updated in the v16test EXPDIR.   gdas prep through fcst and efcs01 were run.    The v16test anal job did NOT execute global_cycle or gaussian_sfcanl.   These jobs were executed in gldas.

The resulting v16ops and v16test surface analysis (tiled and gaussian grid) were compared.   The contents are identical.   The v16ops and v16test gdas fcst and efcs01 also generated identical forecast output.

This test demonstrates that it is possible to move global_cycle and gaussian_sfcanl from the anal job to the gldas without altering cycled results.    A more complete test would be to cycle through 00Z to confirm that both v16ops and v16test correctly ran the gldas part of the gdas job.
